name: thingqbator
description: "Asafetyguide"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  http: ^1.2.2
  provider: ^6.1.2
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^6.1.5
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.0.0
  firebase_database: ^11.2.0  # If using Firebase Database, adjust versions
  firebase_storage: ^12.3.7
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.10
  pin_code_fields: ^8.0.1
  get: ^4.6.6
  pinput: ^5.0.0
  shared_preferences: ^2.1.0
  intl_phone_field: ^3.0.0
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.1       # For date formatting
  flutter_markdown: ^0.7.4+3
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  animate_do: ^3.3.4
  speech_to_text: ^6.1.1
  translator: ^1.0.3+1
  flutter_tts: ^3.8.5
  flutter_typeahead: ^5.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.0.20
  marquee: ^2.1.0
  bootstrap_icons: ^1.11.3
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/female_avatar.png
    - assets/carousel/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: OliveVillage
      fonts:
        - asset: assets/fonts/OliveVillage-Regular.ttf
